### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by pbelyaev** [pbelyaev/laravel-blade-compiler#24]
Now it is laravel-blade-compiler

**Comment by pbelyaev** [comment]
done

**Comment by DanielRuf** [comment]
Under the title you write [Deprecated], is the project really deprecated?

**Comment by pbelyaev** [comment]
@DanielRuf yep, I no longer maintain this project. If you'd like to, you could fork it and continue to work on it.

**Comment by DanielRuf** [comment]
@pbelyaev So no successor of this project? Because deprecated means for me that there is a new project and this is deprecated (different to not maintained).

https://en.wikipedia.org/wiki/Deprecation#Software_deprecation

**Comment by pbelyaev** [comment]
@DanielRuf sorry for the misleading title. I've already changed that to "NOT MAINTAINABLE".

**Comment by DanielRuf** [comment]
I think you mean "NOT MAINTAINED" but thanks for the clarification about the status of the project. I'll probably use this one for a sideproject and provide bugfies and improvements.

Thanks for the work that you have done so far. Have a great day!

**Comment by pbelyaev** [comment]
@DanielRuf thanks for the correction. I wouldn't recommend you to use the package. There are a lot of things that aren't implemented yet. However, If you'd like to implement them, I can transfer the repo to you.
