### ISSUE TITLE
Travis-CI failing

### ISSUE THREAD

**Issue by pdehaan** [pbelyaev/laravel-blade-compiler#6]
Looks like Travis-CI wasn't passing on my previous PR.
https://travis-ci.org/pbelyaev/laravel-blade-parser/builds/154937250

Not sure if we need a .travis.yml file in the top-level (it seems to be defaulting to Ruby server), or if you just want to turn off Travis-CI for this repo. ¯\_(ツ)_/¯

**Comment by pbelyaev** [comment]
@pdehaan I'm on the way to make tests.

**Comment by pbelyaev** [comment]
Done! Thanks for the issue, I wouldn't make the tests without that so soon.
