### ISSUE TITLE
Disable extending

### ISSUE THREAD

**Issue by fortael** [pbelyaev/laravel-blade-compiler#9]
Hey, could you please add the option to disable extending? 
In some case i want to use only `@include` directive. Well, we all noticed, that module just for getting HTML, then bemjson and bemdecl. So, excluding might help to reduce code of enb config (and time), cuz in other case we must use `bemTechs.subtractDeps`. I'm talking about in not all cases we need to have in decl:  _page_, _i-bem_ and etc. I mean
`<script src="/public/views/bundles/all-bem-stuff.js"></script>`
`<script src="/public/views/bundles/exactly-that-bundle.js"></script>`
That make sense for using with laravel, though. 
Thanks.

**Comment by pbelyaev** [comment]
I'd like to do this but have no time. If somebody does I'd merge it :)
